
obj_model: 011_banana
save_base: data/sim
result_base: data/sim/results
scheme: Scheme2
#sweep: snr
sweep: num_samples


comm:
  channel_type: fading
  iscomplex: True
  snr: 20
  min_snr: 0
  max_snr: 20
  snr_interval: 5

sampling:
  require: True
  min_samples: 100
  max_samples: 500
  smp_interval: 100

stl_filename : "${sim.scheme}_${sensing.num_samples}_re_mesh.ply"

snr_sweep:
  base_dir: "${sim.result_base}/snr_sweep/${sim.comm.snr}dB"
  stl_dir : "${sim.snr_sweep.base_dir}/recon_stl"
  csv_dir : "data/main_csv/snr_sweep/${sim.scheme}"

smp_sweep:
  base_dir: "${sim.result_base}/num_sample_sweep/${sim.scheme}"
  stl_dir : "${sim.smp_sweep.base_dir}/recon_stl"
  csv_dir : "data/main_csv/smp_sweep/${sim.scheme}"
