# Copyright (c) Meta Platforms, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# config file for McMaster dataset objects 

obj_model : cotter-pin # cotter-pin, steel-nail, eyebolt
log_id : 0 # Log ID
ablation : False
frame_rate : 10
off_screen : False
render : True
max_length : None
codebook_size : 50000

params: 
  num_particles : 5000
  noise_r : 0.5
  noise_t : 1e-4
  noise_ratio : 1.0 
  interval : 5
