# Copyright (c) Meta Platforms, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# root config for MidasTouch 

defaults:
  - _self_
  - expt: ycb # main experimental params
  - tcn: default # tactile code network params
  - tdn: default # tactile depth network params
  - method: train_data


# obj_model: "035_power_drill"
obj_model: "011_banana"
#obj_model: "048_hammer"
path :
max_samples: 4000
candidate_multiplier: 10  # 후보점은 max_samples의 몇 배로 생성할지 결정
batch_size: 500

render:
  pixmm: 0.03
  width: 240
  height: 320
  cam_dist: 0.022
  shear_mag: 5.0
  pen:
    min: 0.0001
    max: 0.002
  k:
    min: 1000
    max: 20000
  randomize: True
  headless: False
  ###
  pybullet_camera:
    cameraDistance: 0.12
    cameraYaw: 90.
    cameraPitch: -45.
    cameraTargetPosition: [ 0, 0, 0 ]

  digit:
    urdf_path: "urdf/digit.urdf"
    base_position: [ 0, 0, 0 ]

    # quaternion from p.getQuaternionFromEuler([0, -pi/2, 0])
    base_orientation: [ 0.0, -0.707106, 0.0, 0.707106 ]
    use_fixed_base: True

  object:
    urdf_path: "urdf/011_banana.urdf"
    base_position: [ -0.015, 0, 0.04 ]
    global_scaling: 1.0

  ###


noise:
  sig_r: 1  # degrees
  sig_t: 5e-4  # m

num_samples: 10000
total_length: 0.5


# (Optional) hydra settings to prevent job dir changes:
hydra:
  output_subdir: null
  run:
    dir: "."
  job:
    chdir: true