# Copyright (c) Meta Platforms, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# root config for MidasTouch 

defaults:
  - _self_
  - data_config: default
  - k_classifier: default
  - feat_extractor: default
  - graph_mae: mae2
  - expt: ycb # main experimental params
  - sim: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled


obj_model: "011_banana"


path : /home/wireless/Tactile/Research
data_dir: data/sim
#data_dir: sim_main_result/recon
sensing:
#  samples: 3000
  num_samples: 500
  curvature_scale: 1
  candidate_multiplier: 10  # 후보점은 max_samples의 몇 배로 생성할지 결정
  density_boost: 1.0
  area_exponent: 0.5
  density_radius_factor: 50.0
  batch_size: 500
mode : graph

render:
  pixmm: 0.03
  width: 240
  height: 320
#  width: 32
#  height: 32
  cam_dist: 0.022
  shear_mag: 5.0
  pen:
    min: 0.0002
    max: 0.002
  k:
    fixed : 3
    min: 3
    max: 6
    interval: 1
  randomize: True
  headless: False

noise:
  sig_r: 1  # degrees
  sig_t: 5e-4  # m

total_length: 0.5


# (Optional) hydra settings to prevent job dir changes:
hydra:
  output_subdir: null
  run:
    dir: /home/wireless/Tactile/Research
  job:
    chdir: True
