# Copyright (c) Meta Platforms, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# root config for MidasTouch 

defaults:
  - _self_

  - expt: ycb # main experimental params
  - tcn: default # tactile code network params
  - tdn: default # tactile depth network params
  - method: train_data
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled


# obj_model: "035_power_drill"
obj_model: "011_banana"
#obj_model: "048_hammer"
path :

sensing:
  samples: 3000
  min_samples: 100
  num_samples: 3000
  smp_interval: 100
  candidate_multiplier: 10  # 후보점은 max_samples의 몇 배로 생성할지 결정
  density_boost: 1.0
  area_exponent: 0.5
  density_radius_factor: 50.0
  batch_size: 500
mode : "train"

render:
  pixmm: 0.03
  width: 240
  height: 320
  cam_dist: 0.022
  shear_mag: 5.0
  pen:
    min: 0.0002
    max: 0.002
  k:
    min: 1000
    max: 8000
    interval: 1000
  randomize: True
  headless: False

noise:
  sig_r: 1  # degrees
  sig_t: 5e-4  # m

total_length: 0.5

comm:
  iscomplex: False
  snr: 10
  channel_type: "awgn"

model:
  gae:
    epochs: 200
    in_dim: 3
    hid_dim: 64
    latent_dim: 32
    lr: 0.01


sim2:
  max_iterations: 100
  num_next_points : 20


# (Optional) hydra settings to prevent job dir changes:
hydra:
  output_subdir: null
  run:
    dir: "."
  job:
    chdir: false
